### PR TITLE
Added support for filters

### PR DESCRIPTION
**Pull request by Loupax**
Hello everyone, I added filters support and an example filter to your boilerplate :)

### CODE REVIEW

**Comment by jakemmarsh** [comment]
This is great! Would you mind merging master into your branch? I've updated the structure slightly, as well as converted to ES6 syntax.

**Comment by Loupax** [comment]
Just did, but I cannot seem to test it. `gulp dev` gives me the following errors:

    [22:17:28] Failed to load external module babel-core/register
    [22:17:28] Failed to load external module babel/register

**Comment by jakemmarsh** [comment]
Did you run `npm install` after pulling down master? There's the new `babel-core` dependency that sounds like it's missing.

There's just a few things that need updating in your PR then I'm happy to merge it:
- ES6 syntax (mainly `import` instead of `require`)
- rename `filters/_index.js` to `filters/index.js`
- new export/bulk require logic instead of requiring the filtersModule in each filter file. See controllers, services, or directives for an example

**Comment by Loupax** [comment]
Done!

**Comment by jakemmarsh** [comment]
Looks good, thanks for this! :+1:

**Pull request merged**
