### PR TITLE
Add gulp task for revisioning main.js and main.css with a content hash

### PR DESCRIPTION
**Pull request by bvc**
Added a gulp task to revision the main.js and main.css assets.  Basically, this gulp task will append a content hash to the main.css and main.js files (e.g. main.css -> main-a1f3e211.css) and replace the file paths in the index.html file.

### CODE REVIEW

**Comment by mnemanja** [comment]
Yes, would be nice to have a way to clear the cache.

**Comment by mnemanja** [comment]
So, any luck with making this a standard part of the boilerplate?

**Comment by mnemanja** [comment]
This is what I'm getting here:

`"C:\Program Files (x86)\JetBrains\WebStorm 2016.1\bin\runnerw.exe" "C:\Program Files\nodejs\node.exe" C:\www\genolab\genolab-frontend\client.js\src\main\webapp\node_modules\gulp\bin\gulp.js --color --gulpfile c:\www\genolab\genolab-frontend\client.js\src\main\webapp\gulpfile.babel.js prod
[14:52:18] Requiring external module babel-register
[14:52:25] Using gulpfile c:\www\genolab\genolab-frontend\client.js\src\main\webapp\gulpfile.babel.js
[14:52:26] Starting 'clean'...
[14:52:26] Starting 'views'...
[14:52:26] Finished 'views' after 130 ms
[14:52:26] Finished 'clean' after 178 ms
[14:52:26] Starting 'prod'...
[14:52:26] Starting 'views'...
[14:52:26] Starting 'styles'...
[14:52:26] Starting 'images'...
[14:52:26] Starting 'fonts'...
[14:52:26] Starting 'libraries'...
[14:52:26] Finished 'libraries' after 10 ms
[14:52:26] Starting 'browserify'...
[14:52:26] Rebundling...
[14:52:26] Finished 'fonts' after 44 ms
[14:52:27] Finished 'images' after 1.26 s
[14:52:45] Finished 'browserify' after 19 s
[14:52:45] Finished 'views' after 19 s
[14:52:45] Finished 'styles' after 19 s
[14:52:45] Starting 'revisionAssets'...
[14:52:45] DELETED: "c:\www\genolab\genolab-frontend\client.js\src\main\webapp\build\css\main.css"
[14:52:45] DELETED: "c:\www\genolab\genolab-frontend\client.js\src\main\webapp\build\js\main.js"
[14:52:45] Finished 'revisionAssets' after 91 ms
[14:52:45] Starting 'gzip'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, lstat 'c:\www\genolab\genolab-frontend\client.js\src\main\webapp\build\js\main.js'
    at Error (native)

Process finished with exit code 1
`

**Comment by bvc** [comment]
Hey all,

I'm going to close this.  I haven't had much time recently to dig into this on windows or verify that this works across npm versions.  Feel free to clone the branch from my repo or PM me for more details.

**Pull request closed without merging**
