### PR TITLE
Upgrade to Babel 6

### LINKED ISSUE #103: Babel 6
Hi there, 

Are you planning for update to babel 6? Thanks,

### PR DESCRIPTION
**Pull request by DrewML**
Closes #103.

It's important to note that the interop between CommonJS and ES6 modules changed a bit from Babel 5 >> 6. See [this StackOverflow post](http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default) for more info.

Since a `require` statement has to be used when importing modules discovered by `bulk-require`, I've added `.default` to to the index files in each folder (controllers/filters/etc). Having said that, we might want to just export a value with a more descriptive name from each module, instead of using `default`. Maybe `export moduleDescriptor`?

I've also verified that testing in this branch passes with the fixes from #116 applied.

### CODE REVIEW

**Comment by DrewML** [comment]
Have some merge conflicts in here - will get them updated in the next day

**Comment by hassankhan** [comment]
+1

**Comment by hassankhan** [comment]
Pinging for attention :smile:

**Comment by jakemmarsh** [comment]
Done in #133 since this branch wasn't being updated

**Pull request closed without merging**
