### PR TITLE
Add link to the Yeoman generator

### PR DESCRIPTION
**Pull request by alferov**
Hey @jakemmarsh, 
I've implemented yeoman generator that wraps up this boilerplate. I guess it would be pretty convenient for yeoman users (such as myself).

### CODE REVIEW

**Comment by jakemmarsh** [comment]
Sorry for the delay, this is great! Thank you :+1:

**Comment by karneaud** [comment]
Is this still a yeoman generator?

**Comment by alferov** [comment]
Yes, and it's 100% up to date

**Comment by karneaud** [comment]
Hmmmmm had an issue installing via the generator will try again

**Pull request merged**
