### PR TITLE
Proper code coverage for ES6(Babel)

### PR DESCRIPTION
**Pull request by DrewML**
Details about the issue/solution are detailed in #27.

PR also includes a small change mentioned in #27 which removes the "plugins" key in `karma.conf.js`. If this needs to be in a separate PR let me know and I'll cherry-pick the commit out.

### CODE REVIEW

**Comment by jakemmarsh** [comment]
This looks great, thanks for doing it!

Just one question: do we still need the `karma-babel-preprocessor` dependency since we're just using the Babelify transform now?

**Comment by DrewML** [comment]
Good catch - I doubt we do. I'm AFK for part of the day today, but I'll test that out as soon as I'm back at my computer.

**Comment by DrewML** [comment]
@jakemmarsh When you're right, you're right :) -- just pushed an update to the PR.

**Comment by DrewML** [comment]
@jakemmarsh It looks like I actually did things backwards -- we need `karma-babel-preprocessor` during testing (for code coverage to work correctly), but we do *not* need `babelify` during testing.

I squashed the last commits together in this branch to prevent the history from having irrelevant info, but everything should be working now in this PR.

**Comment by jakemmarsh** [comment]
Looks great, thanks for handling this :+1:

**Pull request merged**
