### PR TITLE
Add global.buildType when run `gulp dev` and `gulp prod`. 

### PR DESCRIPTION
**Pull request by yanxi-me**
It is easy to add more build types, and build the results in different build dirs.
Sometimes I want to build more than one for different stages, dev, beta, gamma, prod, they use different configs.

### CODE REVIEW

**Comment by jakemmarsh** [comment]
I like the idea, although it does add a new level of complexity. Would you mind documenting this option/process somewhere in the `README`?

Also, just a question: Is there a reason you moved the `clean` task from being a dependency to being part of the `runSequence`?

**Comment by yanxi-com** [comment]
Thanks @jakemmarsh, I have added the `global.buildType` option description in README.

`clean` task is depend on global.buildType, it will delete entire `build` directory without global.buildType.  So I want it runs after global.buildType is set.

**Comment by jakemmarsh** [comment]
I'm still a bit hesitant to add this new level of complexity. Although it's a good idea for production environments, I'm not sure if it's a good idea to include in a boilerplate. @DrewML, do you have any input on this?

**Comment by DrewML** [comment]
@jakemmarsh Thanks for asking!

1. I like commit 8bf115f. It better follows the style-guide this project follows - https://github.com/toddmotto/angularjs-styleguide#modules

2. I can definitely say that I have had a use for this feature on some older projects I've worked on (where I'm deploying from my local machine to other environments). Having said that, I don't know that I agree with the way this is implemented.

https://github.com/jakemmarsh/angularjs-gulp-browserify-boilerplate/pull/25/files#diff-134b779cc300ce3b71ff78ff10796aa3R5

This line shows an example of how it's used. I'm personally not a big fan of having runtime code that does `if (env)` checks. I feel it sets people up for the opportunity to write more "business logic" inside of those checks, which then becomes a nightmare when testing.

@yanxi-com are there other use-cases for this besides swapping constants that you can describe? I feel like there may be a less complex way of accomplishing that, but I may be overlooking some of the benefits.

**Comment by yanxi-com** [comment]
Thanks @jakemmarsh and @DrewML, there are 2 reason about adding buildType:

1.  make the build results of different buildType in different dirs. Now dev and prod build results are in the same dir. e.g.: I want to deploy prod build result to server, but at the same time I'm using the dev build result in local.
1.  as you mentioned, replace Node-style environment variables in constants(only replace stage specific config, not "business logic").  But the node-style env isn't  running on runtime, it is on build time. e.g.:
 1. source  `process.env.BUILD_TYPE === 'development' ? '/dev/api/v1' : '/prod/api/v1'`
 1. becomes `'production' === 'development' ? '/dev/api/v1' : '/prod/api/v1'` after envify with buildType='production'
 1. become `'/prod/api/v1'` after uglify.

**Pull request closed without merging**
